# Application configuration
server:
  port: 8080
  mode: debug  # debug, release, test

database:
  driver: postgres
  host: localhost
  port: 5432
  user: postgres
  password: password
  name: app_database
  ssl_mode: disable

auth:
  jwt_secret: your-256-bit-secret
  token_expiry: 24h

logging:
  level: info  # debug, info, warn, error
  format: json  # json, text
  output: stdout  # stdout, file

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Authorization
    - Content-Type